// Copy and share must put the identical bytes somewhere.
//
// **That equality is the invariant; everything else about this feature is
// paint.** Copy used to put the bare summary on the clipboard — no title, no
// link, no sign a machine wrote it — so pasted into a chat it read as the
// publisher's own words. The fix is not "share carries attribution": it is
// that both do, because if only one did, copy would become the button people
// use to strip it and the inconsistency would be the bug rather than the
// feature.
//
// The builder is pure and takes strings, so this file needs no widget tree and
// no database. The last group asserts the two call sites really do share it,
// because a pure function tested exhaustively and called by nobody is the
// shape of coverage without the substance.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:flash/services/summary_formatter.dart';

const _title = 'Microsoft proposes limits on its AI';
const _summary = 'The company set out voluntary constraints.\n'
    '- One bullet with a fact in it\n'
    '- A second bullet';
const _disclaimer = 'Generated on-device by Gemini Nano. May not be fully '
    'accurate.';
const _url = 'https://example.com/microsoft-ai-limits';

String _payload({
  String title = _title,
  String summary = _summary,
  String disclaimer = _disclaimer,
  String url = _url,
}) =>
    buildSummaryShareText(
      title: title,
      summary: summary,
      disclaimer: disclaimer,
      url: url,
    );

void main() {
  group('the shape', () {
    test('title, blank, summary, blank, disclaimer, url', () {
      expect(
        _payload(),
        'Microsoft proposes limits on its AI\n'
        '\n'
        'The company set out voluntary constraints.\n'
        '- One bullet with a fact in it\n'
        '- A second bullet\n'
        '\n'
        'Generated on-device by Gemini Nano. May not be fully accurate.\n'
        'https://example.com/microsoft-ai-limits',
      );
    });

    test('the disclaimer and the url are adjacent, with no blank between', () {
      // They read as one footer. A blank line between them makes the URL look
      // like a separate message rather than the source of what is above it.
      expect(_payload(), contains('accurate.\nhttps://example.com'));
    });

    test('the url is last and carries no trailing newline', () {
      // A trailing newline is invisible in a chat and visible in an email
      // subject line preview, and some clients turn it into an empty
      // paragraph.
      expect(_payload(), endsWith(_url));
      expect(_payload().endsWith('\n'), isFalse);
    });

    test('a trailing newline on the model output does not open a gap', () {
      // Nano's output routinely ends with one. On screen it costs nothing;
      // in a message it reads as a mistake.
      expect(_payload(summary: '$_summary\n\n'), _payload());
    });

    test('leading whitespace on the title is trimmed too', () {
      expect(_payload(title: '  $_title '), _payload());
    });
  });

  group('the parts that are not decoration', () {
    // Both of these have a reason that outlives whoever wrote them, so both
    // are asserted rather than assumed.

    test('the link is always present', () {
      // Flash's supply depends on publishers continuing to offer feeds, and an
      // app that circulates their content with no traffic back is the thing
      // publishers close feeds over.
      expect(_payload(), contains(_url));
    });

    test('the disclaimer is always present', () {
      // These summaries are sometimes wrong. Without the label the mistake is
      // attributed to the publisher rather than to the app that generated it.
      expect(_payload(), contains('Gemini Nano'));
    });

    test('the cloud disclaimer travels just as well as the on-device one', () {
      // Both existing strings were written to sit under a summary on screen.
      // Neither uses deixis — no "this", no "above", no "the summary below" —
      // so neither needs the UI around it to make sense, which is why this
      // pass added no ARB key.
      const cloud = 'Generated by Gemini in the cloud. May not be fully '
          'accurate.';
      expect(_payload(disclaimer: cloud), contains(cloud));
      for (final deixis in ['above', 'below', 'this summary']) {
        expect(cloud.toLowerCase(), isNot(contains(deixis)),
            reason: 'a disclaimer that points at the screen stops making '
                'sense the moment it is pasted into a chat');
        expect(_disclaimer.toLowerCase(), isNot(contains(deixis)));
      }
    });
  });

  group('copy and share use the one builder', () {
    // Per the standing rule: a test that constructs its own subject proves a
    // fact about the test. The equality above is a fact about
    // `buildSummaryShareText`; these are the facts about the app.

    final sheet =
        File('lib/screens/article_summary_sheet.dart').readAsStringSync();

    test('both buttons send the same variable', () {
      // The payload is built once into `payload` and handed to both. Two
      // separate `buildSummaryShareText(` calls would also be byte-identical
      // today and would drift the first time one of them gained an argument.
      expect(
          RegExp(r'buildSummaryShareText\(').allMatches(sheet).length, 1,
          reason: 'built more than once in the sheet — build it once and pass '
              'it, or the two payloads can diverge');
      expect(sheet, contains('ClipboardData(text: payload)'));
      expect(sheet, contains('shareSummary(article, payload)'));
    });

    test('copy no longer puts the bare summary on the clipboard', () {
      // The specific regression: `Clipboard.setData(ClipboardData(text:
      // summary))` is what shipped before, and it is one word away from
      // coming back.
      expect(sheet, isNot(contains('ClipboardData(text: summary)')),
          reason: 'copy is back to the unattributed summary');
    });

    test('both share paths go through ShareService', () {
      // One place owns the share sheet. A second `SharePlus.instance.share`
      // anywhere else is a second payload waiting to disagree with this one.
      final strays = <String>[];
      for (final entity in Directory('lib').listSync(recursive: true)) {
        if (entity is! File || !entity.path.endsWith('.dart')) continue;
        final path = entity.path.replaceAll(r'\', '/');
        if (path == 'lib/services/share_service.dart') continue;
        if (entity.readAsStringSync().contains('SharePlus.instance')) {
          strays.add(path);
        }
      }
      expect(strays, isEmpty,
          reason: 'these reach the share sheet directly:\n  '
              '${strays.join('\n  ')}');
    });
  });
}
